// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXHPDxgjPn0sxrzprVEG1ym0w9RwFMasM',
    appId: '1:895946352588:web:7fb30b58ea01aa94645f69',
    messagingSenderId: '895946352588',
    projectId: 'villageissuetracker',
    authDomain: 'villageissuetracker.firebaseapp.com',
    storageBucket: 'villageissuetracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfREU-ioQlv1zSnhdo1YIzxUEgGfLhwkE',
    appId: '1:895946352588:android:20e999a82ed8c522645f69',
    messagingSenderId: '895946352588',
    projectId: 'villageissuetracker',
    storageBucket: 'villageissuetracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXEBM8Dqj0kUzReuRgxcviK0u8rAgAmgg',
    appId: '1:895946352588:ios:fe69d14cd8b88297645f69',
    messagingSenderId: '895946352588',
    projectId: 'villageissuetracker',
    storageBucket: 'villageissuetracker.firebasestorage.app',
    iosBundleId: 'com.example.itemtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXEBM8Dqj0kUzReuRgxcviK0u8rAgAmgg',
    appId: '1:895946352588:ios:fe69d14cd8b88297645f69',
    messagingSenderId: '895946352588',
    projectId: 'villageissuetracker',
    storageBucket: 'villageissuetracker.firebasestorage.app',
    iosBundleId: 'com.example.itemtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXHPDxgjPn0sxrzprVEG1ym0w9RwFMasM',
    appId: '1:895946352588:web:8f2bceb4886b2be5645f69',
    messagingSenderId: '895946352588',
    projectId: 'villageissuetracker',
    authDomain: 'villageissuetracker.firebaseapp.com',
    storageBucket: 'villageissuetracker.firebasestorage.app',
  );
}
